/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as AppRouteImport } from './app'
import { Route as AuthRouteImport } from './auth'
import { Route as AppAccountingRouteImport } from './app.accounting'
import { Route as AppAdminRouteImport } from './app.admin'
import { Route as AppAdvancesRouteImport } from './app.advances'
import { Route as AppAlertsRouteImport } from './app.alerts'
import { Route as AppBalanceSheetRouteImport } from './app.balance-sheet'
import { Route as AppBulkPaymentsRouteImport } from './app.bulk-payments'
import { Route as AppCashFlowRouteImport } from './app.cash-flow'
import { Route as AppCheckerRouteImport } from './app.checker'
import { Route as AppCrmRouteImport } from './app.crm'
import { Route as AppDashboardRouteImport } from './app.dashboard'
import { Route as AppDebtorsRouteImport } from './app.debtors'
import { Route as AppDispatchesRouteImport } from './app.dispatches'
import { Route as AppExpensesRouteImport } from './app.expenses'
import { Route as AppFinanceInvoicesRouteImport } from './app.finance-invoices'
import { Route as AppFinanceProformasRouteImport } from './app.finance-proformas'
import { Route as AppFinancePurchasesRouteImport } from './app.finance-purchases'
import { Route as AppFinanceSalesOrdersRouteImport } from './app.finance-sales-orders'
import { Route as AppForecastRouteImport } from './app.forecast'
import { Route as AppGrnRouteImport } from './app.grn'
import { Route as AppInventoryRouteImport } from './app.inventory'
import { Route as AppInvoicesRouteImport } from './app.invoices'
import { Route as AppNotesRouteImport } from './app.notes'
import { Route as AppProductsRouteImport } from './app.products'
import { Route as AppProfileRouteImport } from './app.profile'
import { Route as AppProformasRouteImport } from './app.proformas'
import { Route as AppPurchaseOrdersRouteImport } from './app.purchase-orders'
import { Route as AppPurchasesRouteImport } from './app.purchases'
import { Route as AppQueueRouteImport } from './app.queue'
import { Route as AppRemindersRouteImport } from './app.reminders'
import { Route as AppReportingRouteImport } from './app.reporting'
import { Route as AppReportsRouteImport } from './app.reports'
import { Route as AppRequestsRouteImport } from './app.requests'
import { Route as AppSalesOrdersRouteImport } from './app.sales-orders'
import { Route as AppSampleDistributionRouteImport } from './app.sample-distribution'
import { Route as AppSettingsRouteImport } from './app.settings'
import { Route as AppStockAllocationRouteImport } from './app.stock-allocation'
import { Route as AppSuppliersRouteImport } from './app.suppliers'
import { Route as AppTasksRouteImport } from './app.tasks'
import { Route as AppTemplateRouteImport } from './app.template'
import { Route as AppVendorsRouteImport } from './app.vendors'
import { Route as AppWarehouseRouteImport } from './app.warehouse'
import { Route as AppWorkspaceRouteImport } from './app.workspace'
import { Route as ApproveTokenRouteImport } from './approve.$token'
import { Route as NoaTokenRouteImport } from './noa.$token'
import { Route as AppChallanDispatchIdRouteImport } from './app.challan.$dispatchId'
import { Route as AppInvoicePreviewIdRouteImport } from './app.invoice-preview.$id'
import { Route as AppNotePreviewIdRouteImport } from './app.note-preview.$id'
import { Route as AppReportingIndexRouteImport } from './app.reporting.index'
import { Route as AppReportingReportRouteImport } from './app.reporting.$report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppBalanceSheetRoute = AppBalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkPaymentsRoute = AppBulkPaymentsRouteImport.update({
  id: '/bulk-payments',
  path: '/bulk-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckerRoute = AppCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchesRoute = AppDispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance-invoices',
  path: '/finance-invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceProformasRoute = AppFinanceProformasRouteImport.update({
  id: '/finance-proformas',
  path: '/finance-proformas',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePurchasesRoute = AppFinancePurchasesRouteImport.update({
  id: '/finance-purchases',
  path: '/finance-purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceSalesOrdersRoute = AppFinanceSalesOrdersRouteImport.update({
  id: '/finance-sales-orders',
  path: '/finance-sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppGrnRoute = AppGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProformasRoute = AppProformasRouteImport.update({
  id: '/proformas',
  path: '/proformas',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportingRoute = AppReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppSampleDistributionRoute = AppSampleDistributionRouteImport.update({
  id: '/sample-distribution',
  path: '/sample-distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStockAllocationRoute = AppStockAllocationRouteImport.update({
  id: '/stock-allocation',
  path: '/stock-allocation',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplateRoute = AppTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehouseRoute = AppWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const ApproveTokenRoute = ApproveTokenRouteImport.update({
  id: '/approve/$token',
  path: '/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NoaTokenRoute = NoaTokenRouteImport.update({
  id: '/noa/$token',
  path: '/noa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChallanDispatchIdRoute = AppChallanDispatchIdRouteImport.update({
  id: '/challan/$dispatchId',
  path: '/challan/$dispatchId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicePreviewIdRoute = AppInvoicePreviewIdRouteImport.update({
  id: '/invoice-preview/$id',
  path: '/invoice-preview/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotePreviewIdRoute = AppNotePreviewIdRouteImport.update({
  id: '/note-preview/$id',
  path: '/note-preview/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportingIndexRoute = AppReportingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportingRoute,
} as any)
const AppReportingReportRoute = AppReportingReportRouteImport.update({
  id: '/$report',
  path: '/$report',
  getParentRoute: () => AppReportingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/balance-sheet': typeof AppBalanceSheetRoute
  '/app/bulk-payments': typeof AppBulkPaymentsRoute
  '/app/cash-flow': typeof AppCashFlowRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/dispatches': typeof AppDispatchesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/finance-invoices': typeof AppFinanceInvoicesRoute
  '/app/finance-proformas': typeof AppFinanceProformasRoute
  '/app/finance-purchases': typeof AppFinancePurchasesRoute
  '/app/finance-sales-orders': typeof AppFinanceSalesOrdersRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/grn': typeof AppGrnRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reporting': typeof AppReportingRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/sample-distribution': typeof AppSampleDistributionRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock-allocation': typeof AppStockAllocationRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/template': typeof AppTemplateRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/warehouse': typeof AppWarehouseRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/challan/$dispatchId': typeof AppChallanDispatchIdRoute
  '/app/invoice-preview/$id': typeof AppInvoicePreviewIdRoute
  '/app/note-preview/$id': typeof AppNotePreviewIdRoute
  '/app/reporting/$report': typeof AppReportingReportRoute
  '/app/reporting/': typeof AppReportingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/balance-sheet': typeof AppBalanceSheetRoute
  '/app/bulk-payments': typeof AppBulkPaymentsRoute
  '/app/cash-flow': typeof AppCashFlowRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/dispatches': typeof AppDispatchesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/finance-invoices': typeof AppFinanceInvoicesRoute
  '/app/finance-proformas': typeof AppFinanceProformasRoute
  '/app/finance-purchases': typeof AppFinancePurchasesRoute
  '/app/finance-sales-orders': typeof AppFinanceSalesOrdersRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/grn': typeof AppGrnRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/sample-distribution': typeof AppSampleDistributionRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock-allocation': typeof AppStockAllocationRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/template': typeof AppTemplateRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/warehouse': typeof AppWarehouseRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/challan/$dispatchId': typeof AppChallanDispatchIdRoute
  '/app/invoice-preview/$id': typeof AppInvoicePreviewIdRoute
  '/app/note-preview/$id': typeof AppNotePreviewIdRoute
  '/app/reporting/$report': typeof AppReportingReportRoute
  '/app/reporting': typeof AppReportingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/balance-sheet': typeof AppBalanceSheetRoute
  '/app/bulk-payments': typeof AppBulkPaymentsRoute
  '/app/cash-flow': typeof AppCashFlowRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/dispatches': typeof AppDispatchesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/finance-invoices': typeof AppFinanceInvoicesRoute
  '/app/finance-proformas': typeof AppFinanceProformasRoute
  '/app/finance-purchases': typeof AppFinancePurchasesRoute
  '/app/finance-sales-orders': typeof AppFinanceSalesOrdersRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/grn': typeof AppGrnRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reporting': typeof AppReportingRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/sample-distribution': typeof AppSampleDistributionRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock-allocation': typeof AppStockAllocationRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/template': typeof AppTemplateRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/warehouse': typeof AppWarehouseRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/challan/$dispatchId': typeof AppChallanDispatchIdRoute
  '/app/invoice-preview/$id': typeof AppInvoicePreviewIdRoute
  '/app/note-preview/$id': typeof AppNotePreviewIdRoute
  '/app/reporting/$report': typeof AppReportingReportRoute
  '/app/reporting/': typeof AppReportingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/balance-sheet'
    | '/app/bulk-payments'
    | '/app/cash-flow'
    | '/app/checker'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/dispatches'
    | '/app/expenses'
    | '/app/finance-invoices'
    | '/app/finance-proformas'
    | '/app/finance-purchases'
    | '/app/finance-sales-orders'
    | '/app/forecast'
    | '/app/grn'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notes'
    | '/app/products'
    | '/app/profile'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reminders'
    | '/app/reporting'
    | '/app/reports'
    | '/app/requests'
    | '/app/sales-orders'
    | '/app/sample-distribution'
    | '/app/settings'
    | '/app/stock-allocation'
    | '/app/suppliers'
    | '/app/tasks'
    | '/app/template'
    | '/app/vendors'
    | '/app/warehouse'
    | '/app/workspace'
    | '/approve/$token'
    | '/noa/$token'
    | '/app/challan/$dispatchId'
    | '/app/invoice-preview/$id'
    | '/app/note-preview/$id'
    | '/app/reporting/$report'
    | '/app/reporting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/balance-sheet'
    | '/app/bulk-payments'
    | '/app/cash-flow'
    | '/app/checker'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/dispatches'
    | '/app/expenses'
    | '/app/finance-invoices'
    | '/app/finance-proformas'
    | '/app/finance-purchases'
    | '/app/finance-sales-orders'
    | '/app/forecast'
    | '/app/grn'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notes'
    | '/app/products'
    | '/app/profile'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reminders'
    | '/app/reports'
    | '/app/requests'
    | '/app/sales-orders'
    | '/app/sample-distribution'
    | '/app/settings'
    | '/app/stock-allocation'
    | '/app/suppliers'
    | '/app/tasks'
    | '/app/template'
    | '/app/vendors'
    | '/app/warehouse'
    | '/app/workspace'
    | '/approve/$token'
    | '/noa/$token'
    | '/app/challan/$dispatchId'
    | '/app/invoice-preview/$id'
    | '/app/note-preview/$id'
    | '/app/reporting/$report'
    | '/app/reporting'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/balance-sheet'
    | '/app/bulk-payments'
    | '/app/cash-flow'
    | '/app/checker'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/dispatches'
    | '/app/expenses'
    | '/app/finance-invoices'
    | '/app/finance-proformas'
    | '/app/finance-purchases'
    | '/app/finance-sales-orders'
    | '/app/forecast'
    | '/app/grn'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notes'
    | '/app/products'
    | '/app/profile'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reminders'
    | '/app/reporting'
    | '/app/reports'
    | '/app/requests'
    | '/app/sales-orders'
    | '/app/sample-distribution'
    | '/app/settings'
    | '/app/stock-allocation'
    | '/app/suppliers'
    | '/app/tasks'
    | '/app/template'
    | '/app/vendors'
    | '/app/warehouse'
    | '/app/workspace'
    | '/approve/$token'
    | '/noa/$token'
    | '/app/challan/$dispatchId'
    | '/app/invoice-preview/$id'
    | '/app/note-preview/$id'
    | '/app/reporting/$report'
    | '/app/reporting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApproveTokenRoute: typeof ApproveTokenRoute
  NoaTokenRoute: typeof NoaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/accounting': {
      id: '/app/accounting'
      path: '/accounting'
      fullPath: '/app/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advances': {
      id: '/app/advances'
      path: '/advances'
      fullPath: '/app/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/balance-sheet': {
      id: '/app/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/app/balance-sheet'
      preLoaderRoute: typeof AppBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bulk-payments': {
      id: '/app/bulk-payments'
      path: '/bulk-payments'
      fullPath: '/app/bulk-payments'
      preLoaderRoute: typeof AppBulkPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cash-flow': {
      id: '/app/cash-flow'
      path: '/cash-flow'
      fullPath: '/app/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checker': {
      id: '/app/checker'
      path: '/checker'
      fullPath: '/app/checker'
      preLoaderRoute: typeof AppCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debtors': {
      id: '/app/debtors'
      path: '/debtors'
      fullPath: '/app/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatches': {
      id: '/app/dispatches'
      path: '/dispatches'
      fullPath: '/app/dispatches'
      preLoaderRoute: typeof AppDispatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-invoices': {
      id: '/app/finance-invoices'
      path: '/finance-invoices'
      fullPath: '/app/finance-invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-proformas': {
      id: '/app/finance-proformas'
      path: '/finance-proformas'
      fullPath: '/app/finance-proformas'
      preLoaderRoute: typeof AppFinanceProformasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-purchases': {
      id: '/app/finance-purchases'
      path: '/finance-purchases'
      fullPath: '/app/finance-purchases'
      preLoaderRoute: typeof AppFinancePurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-sales-orders': {
      id: '/app/finance-sales-orders'
      path: '/finance-sales-orders'
      fullPath: '/app/finance-sales-orders'
      preLoaderRoute: typeof AppFinanceSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecast': {
      id: '/app/forecast'
      path: '/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grn': {
      id: '/app/grn'
      path: '/grn'
      fullPath: '/app/grn'
      preLoaderRoute: typeof AppGrnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proformas': {
      id: '/app/proformas'
      path: '/proformas'
      fullPath: '/app/proformas'
      preLoaderRoute: typeof AppProformasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reporting': {
      id: '/app/reporting'
      path: '/reporting'
      fullPath: '/app/reporting'
      preLoaderRoute: typeof AppReportingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales-orders': {
      id: '/app/sales-orders'
      path: '/sales-orders'
      fullPath: '/app/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sample-distribution': {
      id: '/app/sample-distribution'
      path: '/sample-distribution'
      fullPath: '/app/sample-distribution'
      preLoaderRoute: typeof AppSampleDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock-allocation': {
      id: '/app/stock-allocation'
      path: '/stock-allocation'
      fullPath: '/app/stock-allocation'
      preLoaderRoute: typeof AppStockAllocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/template': {
      id: '/app/template'
      path: '/template'
      fullPath: '/app/template'
      preLoaderRoute: typeof AppTemplateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/warehouse': {
      id: '/app/warehouse'
      path: '/warehouse'
      fullPath: '/app/warehouse'
      preLoaderRoute: typeof AppWarehouseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/approve/$token': {
      id: '/approve/$token'
      path: '/approve/$token'
      fullPath: '/approve/$token'
      preLoaderRoute: typeof ApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noa/$token': {
      id: '/noa/$token'
      path: '/noa/$token'
      fullPath: '/noa/$token'
      preLoaderRoute: typeof NoaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/challan/$dispatchId': {
      id: '/app/challan/$dispatchId'
      path: '/challan/$dispatchId'
      fullPath: '/app/challan/$dispatchId'
      preLoaderRoute: typeof AppChallanDispatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoice-preview/$id': {
      id: '/app/invoice-preview/$id'
      path: '/invoice-preview/$id'
      fullPath: '/app/invoice-preview/$id'
      preLoaderRoute: typeof AppInvoicePreviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/note-preview/$id': {
      id: '/app/note-preview/$id'
      path: '/note-preview/$id'
      fullPath: '/app/note-preview/$id'
      preLoaderRoute: typeof AppNotePreviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reporting/': {
      id: '/app/reporting/'
      path: '/'
      fullPath: '/app/reporting/'
      preLoaderRoute: typeof AppReportingIndexRouteImport
      parentRoute: typeof AppReportingRoute
    }
    '/app/reporting/$report': {
      id: '/app/reporting/$report'
      path: '/$report'
      fullPath: '/app/reporting/$report'
      preLoaderRoute: typeof AppReportingReportRouteImport
      parentRoute: typeof AppReportingRoute
    }
  }
}

interface AppReportingRouteChildren {
  AppReportingReportRoute: typeof AppReportingReportRoute
  AppReportingIndexRoute: typeof AppReportingIndexRoute
}

const AppReportingRouteChildren: AppReportingRouteChildren = {
  AppReportingReportRoute: AppReportingReportRoute,
  AppReportingIndexRoute: AppReportingIndexRoute,
}

const AppReportingRouteWithChildren = AppReportingRoute._addFileChildren(
  AppReportingRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBalanceSheetRoute: typeof AppBalanceSheetRoute
  AppBulkPaymentsRoute: typeof AppBulkPaymentsRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppCheckerRoute: typeof AppCheckerRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppDispatchesRoute: typeof AppDispatchesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinanceProformasRoute: typeof AppFinanceProformasRoute
  AppFinancePurchasesRoute: typeof AppFinancePurchasesRoute
  AppFinanceSalesOrdersRoute: typeof AppFinanceSalesOrdersRoute
  AppForecastRoute: typeof AppForecastRoute
  AppGrnRoute: typeof AppGrnRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProformasRoute: typeof AppProformasRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppReportingRoute: typeof AppReportingRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppSampleDistributionRoute: typeof AppSampleDistributionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockAllocationRoute: typeof AppStockAllocationRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTemplateRoute: typeof AppTemplateRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppWarehouseRoute: typeof AppWarehouseRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppChallanDispatchIdRoute: typeof AppChallanDispatchIdRoute
  AppInvoicePreviewIdRoute: typeof AppInvoicePreviewIdRoute
  AppNotePreviewIdRoute: typeof AppNotePreviewIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAdminRoute: AppAdminRoute,
  AppAdvancesRoute: AppAdvancesRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBalanceSheetRoute: AppBalanceSheetRoute,
  AppBulkPaymentsRoute: AppBulkPaymentsRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppCheckerRoute: AppCheckerRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppDispatchesRoute: AppDispatchesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinanceProformasRoute: AppFinanceProformasRoute,
  AppFinancePurchasesRoute: AppFinancePurchasesRoute,
  AppFinanceSalesOrdersRoute: AppFinanceSalesOrdersRoute,
  AppForecastRoute: AppForecastRoute,
  AppGrnRoute: AppGrnRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppNotesRoute: AppNotesRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProformasRoute: AppProformasRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppQueueRoute: AppQueueRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppReportingRoute: AppReportingRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppSampleDistributionRoute: AppSampleDistributionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockAllocationRoute: AppStockAllocationRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTasksRoute: AppTasksRoute,
  AppTemplateRoute: AppTemplateRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppWarehouseRoute: AppWarehouseRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppChallanDispatchIdRoute: AppChallanDispatchIdRoute,
  AppInvoicePreviewIdRoute: AppInvoicePreviewIdRoute,
  AppNotePreviewIdRoute: AppNotePreviewIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApproveTokenRoute: ApproveTokenRoute,
  NoaTokenRoute: NoaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
