/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAccountingRouteImport } from './routes/app.accounting'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdvancesRouteImport } from './routes/app.advances'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppBalanceSheetRouteImport } from './routes/app.balance-sheet'
import { Route as AppCheckerRouteImport } from './routes/app.checker'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDebtorsRouteImport } from './routes/app.debtors'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppForecastRouteImport } from './routes/app.forecast'
import { Route as AppGrnRouteImport } from './routes/app.grn'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProformasRouteImport } from './routes/app.proformas'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppPurchasesRouteImport } from './routes/app.purchases'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppTemplateRouteImport } from './routes/app.template'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as NoaTokenRouteImport } from './routes/noa.$token'
import { Route as AppInvoicePreviewIdRouteImport } from './routes/app.invoice-preview.$id'
import { Route as AppNotePreviewIdRouteImport } from './routes/app.note-preview.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppBalanceSheetRoute = AppBalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckerRoute = AppCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppGrnRoute = AppGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProformasRoute = AppProformasRouteImport.update({
  id: '/proformas',
  path: '/proformas',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplateRoute = AppTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const NoaTokenRoute = NoaTokenRouteImport.update({
  id: '/noa/$token',
  path: '/noa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoicePreviewIdRoute = AppInvoicePreviewIdRouteImport.update({
  id: '/invoice-preview/$id',
  path: '/invoice-preview/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotePreviewIdRoute = AppNotePreviewIdRouteImport.update({
  id: '/note-preview/$id',
  path: '/note-preview/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/balance-sheet': typeof AppBalanceSheetRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/grn': typeof AppGrnRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/template': typeof AppTemplateRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/invoice-preview/$id': typeof AppInvoicePreviewIdRoute
  '/app/note-preview/$id': typeof AppNotePreviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/balance-sheet': typeof AppBalanceSheetRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/grn': typeof AppGrnRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/template': typeof AppTemplateRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/invoice-preview/$id': typeof AppInvoicePreviewIdRoute
  '/app/note-preview/$id': typeof AppNotePreviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/balance-sheet': typeof AppBalanceSheetRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/grn': typeof AppGrnRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/template': typeof AppTemplateRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/invoice-preview/$id': typeof AppInvoicePreviewIdRoute
  '/app/note-preview/$id': typeof AppNotePreviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/balance-sheet'
    | '/app/checker'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/expenses'
    | '/app/forecast'
    | '/app/grn'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notes'
    | '/app/products'
    | '/app/profile'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reminders'
    | '/app/reports'
    | '/app/requests'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/template'
    | '/app/vendors'
    | '/app/workspace'
    | '/noa/$token'
    | '/app/invoice-preview/$id'
    | '/app/note-preview/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/balance-sheet'
    | '/app/checker'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/expenses'
    | '/app/forecast'
    | '/app/grn'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notes'
    | '/app/products'
    | '/app/profile'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reminders'
    | '/app/reports'
    | '/app/requests'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/template'
    | '/app/vendors'
    | '/app/workspace'
    | '/noa/$token'
    | '/app/invoice-preview/$id'
    | '/app/note-preview/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/balance-sheet'
    | '/app/checker'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/expenses'
    | '/app/forecast'
    | '/app/grn'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notes'
    | '/app/products'
    | '/app/profile'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reminders'
    | '/app/reports'
    | '/app/requests'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/template'
    | '/app/vendors'
    | '/app/workspace'
    | '/noa/$token'
    | '/app/invoice-preview/$id'
    | '/app/note-preview/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  NoaTokenRoute: typeof NoaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/accounting': {
      id: '/app/accounting'
      path: '/accounting'
      fullPath: '/app/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advances': {
      id: '/app/advances'
      path: '/advances'
      fullPath: '/app/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/balance-sheet': {
      id: '/app/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/app/balance-sheet'
      preLoaderRoute: typeof AppBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checker': {
      id: '/app/checker'
      path: '/checker'
      fullPath: '/app/checker'
      preLoaderRoute: typeof AppCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debtors': {
      id: '/app/debtors'
      path: '/debtors'
      fullPath: '/app/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecast': {
      id: '/app/forecast'
      path: '/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grn': {
      id: '/app/grn'
      path: '/grn'
      fullPath: '/app/grn'
      preLoaderRoute: typeof AppGrnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proformas': {
      id: '/app/proformas'
      path: '/proformas'
      fullPath: '/app/proformas'
      preLoaderRoute: typeof AppProformasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/template': {
      id: '/app/template'
      path: '/template'
      fullPath: '/app/template'
      preLoaderRoute: typeof AppTemplateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/noa/$token': {
      id: '/noa/$token'
      path: '/noa/$token'
      fullPath: '/noa/$token'
      preLoaderRoute: typeof NoaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/invoice-preview/$id': {
      id: '/app/invoice-preview/$id'
      path: '/invoice-preview/$id'
      fullPath: '/app/invoice-preview/$id'
      preLoaderRoute: typeof AppInvoicePreviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/note-preview/$id': {
      id: '/app/note-preview/$id'
      path: '/note-preview/$id'
      fullPath: '/app/note-preview/$id'
      preLoaderRoute: typeof AppNotePreviewIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBalanceSheetRoute: typeof AppBalanceSheetRoute
  AppCheckerRoute: typeof AppCheckerRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppForecastRoute: typeof AppForecastRoute
  AppGrnRoute: typeof AppGrnRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProformasRoute: typeof AppProformasRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTemplateRoute: typeof AppTemplateRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppInvoicePreviewIdRoute: typeof AppInvoicePreviewIdRoute
  AppNotePreviewIdRoute: typeof AppNotePreviewIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAdminRoute: AppAdminRoute,
  AppAdvancesRoute: AppAdvancesRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBalanceSheetRoute: AppBalanceSheetRoute,
  AppCheckerRoute: AppCheckerRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppForecastRoute: AppForecastRoute,
  AppGrnRoute: AppGrnRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppNotesRoute: AppNotesRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProformasRoute: AppProformasRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppQueueRoute: AppQueueRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppReportsRoute: AppReportsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTemplateRoute: AppTemplateRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppInvoicePreviewIdRoute: AppInvoicePreviewIdRoute,
  AppNotePreviewIdRoute: AppNotePreviewIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  NoaTokenRoute: NoaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
